# Generated by Django 2.0.7 on 2019-08-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluga', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='itens'),
        ),
    ]
