# Generated by Django 2.0.7 on 2019-08-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluga', '0004_auto_20190824_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('calcados', 'Calçados'), ('roupas', 'Roupas'), ('eletro', 'Eletrodomésticos'), ('imoveis', 'Imóveis'), ('outros', 'Outros')], default='calcados', max_length=16),
        ),
    ]
