# Generated by Django 2.0.7 on 2019-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluga', '0005_auto_20190824_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('Calçados', 'Calçados'), ('Roupas', 'Roupas'), ('Eletrodomésticos', 'Eletrodomésticos'), ('Imóveis', 'Imóveis'), ('Outros', 'Outros')], default='calcados', max_length=16),
        ),
    ]
