# Generated by Django 2.0.7 on 2019-08-24 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluga', '0007_auto_20190824_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^[0-9]*$', 'Apenas números.')]),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='endereco',
            field=models.TextField(),
        ),
    ]
