# Generated by Django 2.0.7 on 2019-09-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluga', '0008_auto_20190824_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
